PUT http://localhost:3003/api/blogs
 {
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12,
    "id": "5a422b3a1b54a676234d17f9"
  }